name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - main  # El pipeline se ejecuta cuando se hace push a la rama 'main'

jobs:

  # 1. Análisis de Seguridad con Snyk
  snyk-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Clona el repositorio

      - name: Install Snyk CLI
        run: npm install -g snyk  # Instala la CLI de Snyk

      - name: Authenticate Snyk CLI
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Token guardado en GitHub Secrets
        run: snyk auth $SNYK_TOKEN

      - name: Snyk test Java dependencies
        run: snyk test --severity-threshold=high  # Analiza vulnerabilidades de severidad alta o mayor

      - name: Generate Snyk JSON Report
        if: always()
        run: |
          echo "Generando reporte JSON de Snyk..."
          snyk test --json > snyk-report.json || echo "Falló snyk test, pero se continúa"
          ls -lh snyk-report.json || echo "No se generó el reporte"

      - name: Upload Snyk JSON Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json

  # 2. Pruebas unitarias y cobertura con JaCoCo
  test:
    name: Run Tests with JaCoCo
    runs-on: ubuntu-latest
    needs: snyk-scan  # Solo se ejecuta si pasó el escaneo de Snyk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build and test
        run: mvn clean verify  # Ejecuta los tests y genera reporte de cobertura JaCoCo

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

  # 3. Análisis de calidad de código con SonarCloud
  sonar-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: test  # Solo se ejecuta si pasaron los tests
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

            
      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token SonarCloud desde Secrets
        run: |
          mvn verify sonar:sonar \
            -Dsonar.projectKey=GabrielGrobier_Jacoco-sonacloud \
            -Dsonar.organization=gabrielgrobier \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN}

  # 4. Empaquetado final de la aplicación
  build:
    name: Build Jar
    runs-on: ubuntu-latest
    needs: sonar-analysis  # Solo se ejecuta si pasa el análisis de calidad

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Package application
        run: mvn clean package -DskipTests  # Empaqueta sin volver a ejecutar pruebas

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar  # Sube el .jar como artefacto del pipeline
